apiVersion: v1
kind: Secret
metadata:
  name: simple-webhook-certs
  namespace: default
data:
# 请将 <base64-encoded tls.crt> 和 <base64-encoded tls.key> 
# 替换为您生成的证书和密钥的 Base64 编码字符串。可以使用以下命令来获取这些字符串：
# cat tls.crt | base64 | tr -d '\n'
# cat tls.key | base64 | tr -d '\n'
  tls.crt: <base64-encoded tls.crt>
  tls.key: <base64-encoded tls.key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webhook
  template:
    metadata:
      labels:
        app: simple-webhook
    spec:
      containers:
      - name: webhook-server
        image: simple-webhook:latest
        volumeMounts:
        - name: certs
          mountPath: "/certs"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: simple-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webhook
  namespace: default
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: simple-webhook
